# Generated by Django 5.0 on 2023-12-15 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=100)),
                ('protein', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('carbs', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('fats', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('total_calories', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
