# Generated by Django 5.0 on 2023-12-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories_counter', '0002_activity_rename_food_foods_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Activities',
        ),
    ]
