# Generated by Django 4.2.4 on 2023-10-24 08:03

from django.db import migrations


def create_unique_brands(apps, schema_editor):
    shoes = apps.get_model('main_app', 'Shoe')
    unique_brands = apps.get_model('main_app', 'UniqueBrands')

    for el in shoes.brand.all().distincts():
        unique_brands.create(brand_name=el)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
    ]
