# Generated by Django 4.2.4 on 2023-10-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lasts_name',
            new_name='last_name',
        ),
    ]
