# Generated by Django 5.0 on 2023-12-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_counter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories_per_hour', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='food',
            new_name='name',
        ),
        migrations.AddField(
            model_name='people',
            name='total_calories',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
